### PR TITLE
Fix some bug on the fetch-pipe

### LINKED ISSUE #184: Intermittent iteration bug occurred when fetching topic records
### Reappearance
* terminate a broker, a accelerator server and a inferencer node after publish some topic records
* turn all nodes with `broker -> accelerator -> inferencer` order
* The fetch_pipe cannot consume newly records sometimes
### Reason 
* Maybe there is some bug on iteratation logic of fetch pipe
* Re-seeking a tailing iterator with wrong offset seems to be a problem

### PR DESCRIPTION
**Pull request by elon0823**
close #184 

I fixed wrong offset seeking code from fetch-pipe. The `iterateRecords` logic is much more simplified.

### CODE REVIEW

File: broker/pipeline/fetch_pipe.go [hunk 1]
```diff
@@ -83,18 +84,18 @@ func (f *FetchPipe) Ready(inStream <-chan interface{}) (<-chan interface{}, <-ch
...
-	first := true
-	prevKey := storage.NewRecordKeyFromData(topicName, fragmentId, startOffset)
 	it := f.db.Scan(storage.RecordCF)
 
 	prefix := make([]byte, len(topicName)+1+int(unsafe.Sizeof(uint32(0))))
 	copy(prefix, topicName+"@")
 	binary.BigEndian.PutUint32(prefix[len(topicName)+1:], fragmentId)
-	iterateInterval := time.Millisecond * 10
-	timer := time.NewTimer(iterateInterval)
+	waitInterval := time.Millisecond * 500
```
Comment (1dennispark) [inline broker/pipeline/fetch_pipe.go:92]: wait 시간이 길어진거 같은데요. 이유가 뭘까요?

**Review by 1dennispark — CHANGES_REQUESTED** [review]

File: broker/pipeline/fetch_pipe.go (hunk 1 above)
Comment (elon0823) [reply broker/pipeline/fetch_pipe.go:92]: I changed it for testing. I'll revert it.
